### ISSUE TITLE
Acessibilidade

### ISSUE THREAD

**Issue by DidoReis** [DidoReis/Insepnew#1]
Por favor colocar as correções necessárias para a acessibilidade.
Obrigado

**Comment by adrianagardin** [comment]
teste de report de issue, para ver se está funcionando pra mim...

**Comment by flaviorscorreia** [comment]
Os links do menu estão com o atributo "aria-label", no entanto, como o rótulo do href já está declarado, este atributo é dispensável, além disso o uso da palavra "link" junto ao valor de cada aria-label, faz com que o leitor de telas leia duas vezes a palavra link. Assim sendo, recomendamos remover o aria-label.
