### ISSUE TITLE
Inserir significado da sigla ESG

### ISSUE THREAD

**Issue by adrianagardin** [DidoReis/Insepnew#11]
Na seção Público de Interesse, complementar a caixinha "profissionais de que atuam com ESG" com o texto da sigla "Environmental Social Governance". A pessoa  pode não entender o que significa ESG, portanto devemos incluir o texto.

**Comment by DidoReis** [comment]
Adicionei um aria-label='Environmental Social Governance', caso seja para adicionar na caixa visível no site temos que ver com o Guilherme como ajustar esse texto dentro da caixa para ajustar o design

**Comment by DidoReis** [comment]
Foi adicionado a descrição.
