### ISSUE TITLE
Ajustar títulos nível 2 e 3.

### ISSUE THREAD

**Issue by adrianagardin** [DidoReis/Insepnew#12]
Na seção "o INSEP oferece benefícios únicos", este é nível 2. Os títulos das caixinhas abaixo são nível 3.
Da mesma forma na seção "conteúdo programático", esta é nível 2. Os títulos dos módulos "básico, intermediário e avançado" são nível 3.

**Comment by DidoReis** [comment]
Corrigido, mantido o H2 no "o INSEP oferece benefícios únicos" e os demais substituído por h3

**Comment by adrianagardin** [comment]
ok, testado no NVDA com sucesso
