### ISSUE TITLE
Deixar os bullets da lista como elemento decorativo ( conteúdo programático)

### ISSUE THREAD

**Issue by adrianagardin** [DidoReis/Insepnew#14]
Na seção conteúdo programático, dentro das caixinhas, o leitor fica lendo todos os bullets da lista como imagem.

**Comment by DidoReis** [comment]
Corrigido adicionando um aria-hidden="true" que fez com que o leitor de tela não leia os bullets

**Comment by adrianagardin** [comment]
testado no NVDA com sucesso
