### ISSUE TITLE
seção Equipe INSEP 

### ISSUE THREAD

**Issue by adrianagardin** [DidoReis/Insepnew#15]
o leitor lê "seção EQUIPE INSEP, título nível 2 equipe INSEP" quando deveria ler apenas "título nível 2 equipe INSEP"

**Comment by DidoReis** [comment]
Aqui havia um aria-label="Seção Equipe Insep" por isso ele lia primeiro "seção Equipe Insep", foi removido o aria-label="Seção Equipe Insep" para que leia somente o H2

**Comment by adrianagardin** [comment]
ok, testado no NVDA com sucesso
