### ISSUE TITLE
Complementar o botão "seguir no LInkedin" com o respectivo nome da pessoa.

### ISSUE THREAD

**Issue by adrianagardin** [DidoReis/Insepnew#16]
A pessoa cega pode perder a referência espacial durante a navegação por botões.

**Comment by DidoReis** [comment]
adicionado aria-label="Seguir nome de cada um da equipe no LinkedIn" e adicionado um aria-hidden='true' para que não leia seguir no linkedin duplicado

**Comment by adrianagardin** [comment]
testado no NVDA com sucesso!
