### ISSUE TITLE
<ul> e <ol> devem conter apenas elementos <li>, <script> ou <template> diretamente

### ISSUE THREAD

**Issue by adrianagardin** [DidoReis/Insepnew#19]
Certifique-se de que todas as listas ordenadas e não ordenadas (definidas por elementos ulou ol) contenham apenas elementos li de conteúdo .

**Comment by DidoReis** [comment]
Em reunião com o Flavio ele falou que isso provavelmente foi um falso diagnóstico do access (acho que é esse o software) que 
o menu está correto
