### ISSUE TITLE
Os níveis de título devem aumentar apenas um

### ISSUE THREAD

**Issue by adrianagardin** [DidoReis/Insepnew#20]
Certifique-se de que os títulos estejam em uma ordem lógica. Por exemplo, verifique se todos os títulos estão marcados com elementos h1 até h6 e se estão ordenados hierarquicamente. Por exemplo, o nível do cabeçalho após um h1 deve ser um h2, não um h3.
Quando temos quebras de sessão a hierarquia retrocede ao cabeçalho anterior da sessão principal.

**Comment by DidoReis** [comment]
Verificado e corrigido os níveis de títulos, acho que está correto. rs

**Comment by adrianagardin** [comment]
testado no NVDA com sucesso, mas deixarei a equipe INSEP validar antes de fechar essa issue

**Comment by DidoReis** [comment]
Em reunião com o Flavio ele informou que os níveis de titulos estão corretos.
