### ISSUE TITLE
Componente de WhatsApp

### ISSUE THREAD

**Issue by adrianagardin** [DidoReis/Insepnew#21]
O texto alternativo deve ser apenas "WhatsApp".
Necessário que exista um "title" = "site externo"

**Comment by DidoReis** [comment]
Removido o icone do e deixei só Whatsapp e adicione também o title = site externo

**Comment by adrianagardin** [comment]
Vou deixar para Flavio validar esse item, pois não consegui identificar se está correto.

**Comment by DidoReis** [comment]
Em reunião com o Flavio ele informou que as correções do whatsapp estão corretas.
