### ISSUE TITLE
Componente de Vlibras

### ISSUE THREAD

**Issue by adrianagardin** [DidoReis/Insepnew#22]
Deve ser um botão e não um link.
Este elemento na ordem de navegação por tab deve ser após o "WhatsApp" e depois seguindo a ordem de navegação por tab, seguir o restante dos elementos que recebem foco.

**Comment by DidoReis** [comment]
Vlibras adicionado como botão e o foco ajustado com o tabIndex no whatsapp e depois o Vlibras

**Comment by adrianagardin** [comment]
Vou deixar essa issue para Flavio validar, pois não consigo identificar se está correto.

**Comment by flavio** [comment]
@adrianagardin I think you mentioned the wrong Flavio :smiley:

**Comment by DidoReis** [comment]
Em conversa com o Flavio ele foi falando as sequências que o leito lia os botões e imagens e primeiro foi lido o whatsapp e depois o Vlibras.

**Comment by adrianagardin** [comment]
Podemos concluir essa issue?

**Comment by DidoReis** [comment]
Perdão eu havia esquecido
