### ISSUE TITLE
Ajustar fonte dos textos do site

### ISSUE THREAD

**Issue by adrianagardin** [DidoReis/Insepnew#23]
Gui irá alterar o protótipo para deixar tudo com a mesma fonte. É importante ter um padrão para pessoas que são neurodiversas

**Comment by DidoReis** [comment]
Todas as fontes foram modificadas para roboto como padrão do site todo.

**Comment by adrianagardin** [comment]
Vamos nos reunir com Gui para repassar os elementos que mudaram texto, em função da conversão de fonte

**Comment by DidoReis** [comment]
Tudo já está em Roboto
