### ISSUE TITLE
retirar a palavra logotipo da seção Onde nossos Alunos trabalham

### ISSUE THREAD

**Issue by adrianagardin** [DidoReis/Insepnew#24]
O leitor fica lendo "logotipo + empresa" para cada logo. Fica repetitivo. Deixar apenas o nome da empresa.

**Comment by DidoReis** [comment]
Retirado todos os logotipos da seção

**Comment by adrianagardin** [comment]
a palavra logotipo foi de fato retirada, mas o leitor agora lê "gráfico itaú, gráfico santander"... é possível retirar essa palavra gráfico e deixar somente o nome da empresa?

**Comment by DidoReis** [comment]
Então no código no alt="" está somente o nome da empresa não tem gráfico na descrição. Não será algo no NVDA amanhã pergunto para o Flavio

**Comment by DidoReis** [comment]
Em reunião com o Flavio ele informou que a  palavra gráfico vem por padrão no NVDA.
Issue encerrada!

**Comment by DidoReis** [comment]
OK
