### ISSUE TITLE
botões claro/escuro

### ISSUE THREAD

**Issue by adrianagardin** [DidoReis/Insepnew#25]
precisa colocar um texto para acessibilidade nesse botão...
ARIA LABEL
 quando o site estiver no modo claro "alternar para modo escuro"
 quando estiver no modo escuro "alternar para modo claro"

**Comment by DidoReis** [comment]
aria-label={darkTheme ? 'alternar para modo claro' : ' alternar para modo escuro'} 
Corrigido
