### ISSUE TITLE
Logo INSEP

### ISSUE THREAD

**Issue by adrianagardin** [DidoReis/Insepnew#4]
O leitor lê INSEP como "Instituto Esportivo paraatleta." Gostaríamos que deixasse somente INSEP mesmo.

**Comment by DidoReis** [comment]
Tirei do alt o "Instituto Esportivo paraatleta." e só deixei INSEP

**Comment by adrianagardin** [comment]
no NVDA ainda lê "Instituto Esportivo paraatleta" Tirar dúvida com Flavio
