### ISSUE TITLE
Imagem decorativa principal com elementos desagrupados

### ISSUE THREAD

**Issue by adrianagardin** [DidoReis/Insepnew#5]
Quando navegamos usando leitor usando seta para baixo, o leitor lê alguns elementos da imagem como "fora de lista gráfico clicável", dando impressão de que existem elementos na imagem que estão desagrupados, OU que não está sendo lido corretamente o elemento Whatsapp

**Comment by DidoReis** [comment]
Foram corrigidas as imagens e suas descrições acredito que tenha sido corrigido

**Comment by adrianagardin** [comment]
Quando testado no NVDA, ainda aparece um leitura confusa dos primeiros elementos da página. Não consegui identificar o erro, acho melhor tirar essa dúvida com Flávio.

**Comment by DidoReis** [comment]
Descobrimos que esse gráfico que está fora de lista clicável é o botão de dark or light que está codado como SVG.
Irei corrigir ainda.

**Comment by DidoReis** [comment]
Foi corrigido adiciona a role=button para deixar de ler o botão como imagem
