### ISSUE TITLE
Ajustar hierarquia do texto "Aprenda sobre acessibilidade digital"

### ISSUE THREAD

**Issue by adrianagardin** [DidoReis/Insepnew#7]
Por ser o primeiro e mais importante, o título "Aprenda sobre acessibilidade digital" deve ser de nível 1. O "Aprenda sobre acessbilidade" pode ser texto mesmo

**Comment by DidoReis** [comment]
Não seria "Seja um especialista em acessibilidade digital" ao invés de aprenda sobre acessibilidade digital? se for a primeira opção foi corrigido

**Comment by adrianagardin** [comment]
ok, testado com sucesso no NVDA
